# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Neil Ramsay
description: > # this means to ignore newlines until "baseurl:"
  Technical Ramblings of Neil Ramsay.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://neilramsay.github.io" # the base hostname & protocol for your site
twitter_username: neilramsaytech
github_username:  neilramsay

# Build settings
markdown: kramdown

# Custom settings
safe: true
